apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    metadata:
      labels:
        app: batch-app
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job