apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-8g
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/rabbitmq-8g"
---

