apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  selector:
    app: kubia-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port:
  