apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  labels:
    app: kubia-rc
spec:
  replicas: 3
  selector:
    app: kubia-rc
  template:
    metadata:
      labels:
        app: kubia-rc
    spec:
      containers:
        - name: kubia-rc
          image: luksa/kubia
          ports:
            - containerPort: 8080
  