apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-8g
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/prom-8g"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-2g
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/prom-2g"