apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    "<base64 encoded ~/.dockercfg file>"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  imagePullSecrets:
    - name: dockersecret
  containers:
    - image: username/private:tag
      name: main