apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-8g
  namespace: minio
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/minio-8g"
