apiVersion: v1
kind: Pod
metadata:
  name: Title
  labels:
    zone: china
    cluster: test-cluster
  annotations:
    build: two
    builder: join-node
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh","-C"]
      args:
        - while true;do
          if [[ -e /etc/podinfo/lables ]]; then
            echo '\n\n';cat /etc/podinfo/labels;fi;
          if [[ -e /etc/podinfo/annotations ]]; then
          echo '\n\n';cat /etc/podinfo/annotations;fi;
          sleep 10;
         done;
      volumeMounts:
        - mountPath: podinfo
          name: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations