apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-withlabel
  labels:
    env: prod
    app: kubia-manual
spec:
  containers:
    - name: kubia-manual
      image: luksa/kubia
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          protocol: TCP
#  restartPolicy: Always